In [1]:
import numpy as np


In [6]:
liste=np.arange(0,10)

In [7]:
liste

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
liste[5]

5

In [9]:
liste[3:5]

array([3, 4])

In [16]:
liste[3:8] = -1

In [17]:
liste

array([ 0,  1,  2, -1, -1, -1, -1, -1,  8,  9])

# slicing numpyarray

In [18]:
nparray=np.arange(0,24)

In [19]:
nparray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
nparray[4:9]

array([4, 5, 6, 7, 8])

In [37]:
slicingdizi=nparray[4:9]

In [49]:
slicingdizi=(nparray[4:9] == 700)

In [50]:
nparray

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

# slicing yaparken ana veriyi kaybetmemek gerekirse dizinin kopyası üzerinden işlem yapılmalıdır.aşağıdaki gibi

In [51]:
dizi=np.arange(10,30)

In [52]:
dizi

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [56]:
kopyadizi=dizi.copy()

In [57]:
kopyadizi

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [58]:
kopyadizislicing=kopyadizi[3:10]

In [59]:
kopyadizislicing

array([13, 14, 15, 16, 17, 18, 19])

In [60]:
kopyadizislicing[:] = 800

In [61]:
kopyadizislicing

array([800, 800, 800, 800, 800, 800, 800])

In [62]:
kopyadizi

array([ 10,  11,  12, 800, 800, 800, 800, 800, 800, 800,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29])

In [63]:
dizi

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])